export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';


export const WITHDRAWAL_REQUEST = 'WITHDRAWAL_REQUEST';
export const WITHDRAWAL_SUCCESS = 'WITHDRAWAL_SUCCESS';
export const WITHDRAWAL_FAIL = 'WITHDRAWAL_FAIL';


export const LODGEMENT_REQUEST = 'LODGEMENT_REQUEST';
export const LODGEMENT_SUCCESS = 'LODGEMENT_SUCCESS';
export const LODGEMENT_FAIL = 'LODGEMENT_FAIL';


export const TRANSFER_REQUEST = 'TRANSFER_REQUEST';
export const TRANSFER_SUCCESS = 'TRANSFER_SUCCESS';
export const TRANSFER_FAIL = 'TRANSFER_FAIL';